name: 'automated_testing_framework_plugin_firestore'
description: "Library to use Google's Firestore as a storage mechanism for automated tests and test results."
homepage: 'https://github.com/peiffer-innovations/automated_testing_framework_plugin_firestore'
version: '5.0.0+2'

environment: 
  sdk: '>=2.17.0 <3.0.0'

dependencies: 
  automated_testing_framework: '^4.0.1+2'
  automated_testing_framework_plugin_firebase_storage: '^5.0.0+1'
  cloud_firestore: '^3.1.17'
  firebase_auth: '^3.3.19'
  firebase_core: '^1.17.1'
  firebase_storage: '^10.2.17'
  flutter: 
    sdk: 'flutter'
  form_validation: '^2.1.0+3'
  json_class: '^2.1.2+5'
  logging: '^1.0.2'
  static_translations: '^2.1.1+1'

dev_dependencies: 
  flutter_test: 
    sdk: 'flutter'


flutter: 
  uses-material-design: true
