name: automated_testing_framework_plugin_firestore
description: Library to use Google's Firestore as a storage mechanism for automated tests and test results.
homepage: https://github.com/peiffer-innovations/automated_testing_framework_plugin_firestore

version: 3.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  automated_testing_framework: ^3.0.0
  automated_testing_framework_plugin_firebase_storage: ^3.0.0
  cloud_firestore: ^1.0.0
  firebase_auth: ^1.0.0
  firebase_core: ^1.0.0
  firebase_storage: ^8.0.0
  flutter:
    sdk: flutter
  form_validation: ^2.0.0
  json_class: ^2.0.0
  logging: ^1.0.0
  static_translations: ^2.0.0

# dependency_overrides:
#   automated_testing_framework:
#     path: ../automated_testing_framework
#   automated_testing_framework_models:
#     path: ../automated_testing_framework_models
#   automated_testing_framework_plugin_firebase_storage:
#     path: ../automated_testing_framework_plugin_firebase_storage

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
