name: 'automated_testing_framework_plugin_firestore'
description: "Library to use Google's Firestore as a storage mechanism for automated tests and test results."
homepage: 'https://github.com/peiffer-innovations/automated_testing_framework_plugin_firestore'
version: '5.0.2+1'

environment: 
  sdk: '>=2.19.0 <4.0.0'

dependencies: 
  automated_testing_framework: '^5.0.0+1'
  automated_testing_framework_plugin_firebase_storage: '^5.0.1'
  cloud_firestore: '^4.3.1'
  firebase_auth: '^4.2.5'
  firebase_core: '^2.4.1'
  firebase_storage: '^11.0.10'
  flutter: 
    sdk: 'flutter'
  form_validation: '^2.2.0+6'
  json_class: '^2.1.5+1'
  logging: '^1.1.1'
  static_translations: '^2.1.2+1'

dev_dependencies: 
  flutter_test: 
    sdk: 'flutter'


dependency_overrides: 
  intl: '^0.18.0'

flutter: 
  uses-material-design: true

ignore_updates: 
  - 'archive'
  - 'async'
  - 'boolean_selector'
  - 'characters'
  - 'charcode'
  - 'collection'
  - 'clock'
  - 'crypto'
  - 'fake_async'
  - 'file'
  - 'matcher'
  - 'material_color_utilities'
  - 'meta'
  - 'path'
  - 'source_span'
  - 'stack_trace'
  - 'stream_channel'
  - 'string_scanner'
  - 'sync_http'
  - 'term_glyph'
  - 'test_api'
  - 'typed_data'
  - 'vector_math'
  - 'webdriver'
