name: 'automated_testing_framework_plugin_firestore'
description: "Library to use Google's Firestore as a storage mechanism for automated tests and test results."
homepage: 'https://github.com/peiffer-innovations/automated_testing_framework_plugin_firestore'
version: '5.0.0+5'

environment: 
  sdk: '>=2.17.0 <3.0.0'

dependencies: 
  automated_testing_framework: '^4.0.1+6'
  automated_testing_framework_plugin_firebase_storage: '^5.0.0+5'
  cloud_firestore: '^3.1.18'
  firebase_auth: '^3.3.20'
  firebase_core: '^1.18.0'
  firebase_storage: '^10.2.18'
  flutter: 
    sdk: 'flutter'
  form_validation: '^2.1.0+7'
  json_class: '^2.1.2+7'
  logging: '^1.0.2'
  static_translations: '^2.1.1+4'

dev_dependencies: 
  flutter_test: 
    sdk: 'flutter'


flutter: 
  uses-material-design: true
