name: automated_testing_framework_plugin_firestore
description: Library to use Google's Firestore as a storage mechanism for automated tests and test results.
homepage: https://github.com/peiffer-innovations/automated_testing_framework_plugin_firestore

version: 3.0.1+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  automated_testing_framework: ^3.1.0
  automated_testing_framework_plugin_firebase_storage: ^3.0.1
  cloud_firestore: ^2.2.2
  firebase_auth: ^1.4.1
  firebase_core: ^1.3.0
  firebase_storage: ^8.1.3
  flutter:
    sdk: flutter
  form_validation: ^2.0.0
  json_class: ^2.0.0+1
  logging: ^1.0.1
  static_translations: ^2.0.2

# dependency_overrides:
#   automated_testing_framework:
#     path: ../automated_testing_framework
#   automated_testing_framework_models:
#     path: ../automated_testing_framework_models
#   automated_testing_framework_plugin_firebase_storage:
#     path: ../automated_testing_framework_plugin_firebase_storage

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
